default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 12345678

development:
  <<: *default
  database: photoupload_dev

test:
  <<: *default
  database: photoupload_test

production:
  url: <%= ENV['DATABASE_URL'] %>
